import asyncio

import pytest
from sqlalchemy import inspect, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import create_async_engine

from app.database import Base, configure_sqlite_engine
from app.services.rule_packages.kmai_mapping_contracts import (
    KmaiMappingCreateRequest,
    KmaiMappingUpdateRequest,
)
from app.services.db_schema_maintenance import ensure_project_schema


def test_manual_factor_contracts_reject_client_generated_factor_keys():
    request = {
        "scope": "project",
        "project_id": 1,
        "source_field": "cad.features",
        "source_value": "custom feature",
        "mapping_mode": "manual_factor",
        "target_factor_key": "client_generated_key",
        "target_factor_name": "Custom feature",
    }

    with pytest.raises(ValueError, match="generated by the server"):
        KmaiMappingCreateRequest.model_validate(request)

    with pytest.raises(ValueError, match="generated by the server"):
        KmaiMappingUpdateRequest.model_validate(
            {"expected_revision": 1, "mapping_mode": "manual_factor", "target_factor_key": "client_generated_key"}
        )


def test_kmai_mapping_schema_is_idempotent_and_preserves_audit_history(tmp_path):
    async def run():
        engine = create_async_engine(f"sqlite+aiosqlite:///{tmp_path / 'kmai.db'}")
        configure_sqlite_engine(engine)
        try:
            async with engine.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
                await ensure_project_schema(conn)
                await ensure_project_schema(conn)
                tables = {
                    row[0]
                    for row in (await conn.execute(text("SELECT name FROM sqlite_master WHERE type='table'"))).all()
                }
                assert {
                    "kmai_factor_mappings",
                    "kmai_factor_mapping_events",
                    "kmai_factor_mapping_usages",
                } <= tables
                indexes = {
                    row[0]
                    for row in (await conn.execute(text("SELECT name FROM sqlite_master WHERE type='index'"))).all()
                }
                assert "uq_kmai_factor_mappings_global_source" in indexes
                assert "uq_kmai_factor_mappings_project_source" in indexes
                foreign_keys = {
                    table: {
                        (row[3], row[2], row[6].upper())
                        for row in (await conn.execute(text(f"PRAGMA foreign_key_list({table})"))).all()
                    }
                    for table in (
                        "kmai_factor_mappings",
                        "kmai_factor_mapping_events",
                        "kmai_factor_mapping_usages",
                    )
                }
                assert ("project_id", "projects", "CASCADE") in foreign_keys["kmai_factor_mappings"]
                assert ("mapping_id", "kmai_factor_mappings", "SET NULL") in foreign_keys["kmai_factor_mapping_events"]
                assert ("mapping_id", "kmai_factor_mappings", "RESTRICT") in foreign_keys["kmai_factor_mapping_usages"]
                assert ("package_id", "finalized_rule_packages", "CASCADE") in foreign_keys["kmai_factor_mapping_usages"]

                await conn.execute(text("INSERT INTO projects (id, name) VALUES (1, 'one'), (2, 'two')"))
                await conn.execute(text("""
                    INSERT INTO kmai_factor_mappings
                    (scope, project_id, source_field, source_value, mapping_mode,
                     target_factor_key, target_factor_name, target_factor_category)
                    VALUES ('global', NULL, 'cad.features', 'slot', 'existing_factor',
                            'has_slot_feature', 'Slot', 'cad'),
                           ('project', 1, 'cad.features', 'slot', 'existing_factor',
                            'has_slot_feature', 'Slot', 'cad')
                """))
                with pytest.raises(IntegrityError):
                    await conn.execute(text("""
                        INSERT INTO kmai_factor_mappings
                        (scope, project_id, source_field, source_value, mapping_mode,
                         target_factor_key, target_factor_name, target_factor_category)
                        VALUES ('project', 1, 'cad.features', 'slot', 'existing_factor',
                                'has_slot_feature', 'Slot', 'cad')
                    """))
                await conn.execute(text("""
                    INSERT INTO kmai_factor_mappings
                    (scope, project_id, source_field, source_value, mapping_mode,
                     target_factor_key, target_factor_name, target_factor_category)
                    VALUES ('project', 2, 'cad.features', 'slot', 'existing_factor',
                            'has_slot_feature', 'Slot', 'cad')
                """))
                with pytest.raises(IntegrityError):
                    await conn.execute(text("""
                        INSERT INTO kmai_factor_mappings
                        (scope, project_id, source_field, source_value, mapping_mode,
                         target_factor_key, target_factor_name, target_factor_category)
                        VALUES ('global', NULL, 'cad.features', 'slot', 'existing_factor',
                                'has_slot_feature', 'Slot', 'cad')
                    """))
                await conn.execute(text("""
                    INSERT INTO kmai_factor_mapping_events
                    (mapping_id, action, actor, before_json, after_json)
                    VALUES (1, 'created', 'tester', '{"before": null}', '{"after": 1}')
                """))
                await conn.execute(text("""
                    INSERT INTO finalized_rule_packages
                    (id, project_id, version, package_name, schema_version, status)
                    VALUES (1, 1, 1, 'pkg', '1.0', 'published')
                """))
                await conn.execute(text("""
                    INSERT INTO kmai_factor_mapping_usages
                    (mapping_id, package_id, revision, mapping_snapshot_json)
                    VALUES (1, 1, 1, '{"mapping_id": 1}')
                """))
                await conn.execute(text("DELETE FROM finalized_rule_packages WHERE id = 1"))
                assert (await conn.execute(text("SELECT COUNT(*) FROM kmai_factor_mapping_usages"))).scalar_one() == 0
                await conn.execute(text("DELETE FROM kmai_factor_mappings WHERE id = 1"))
                event = (await conn.execute(text("SELECT mapping_id, before_json, after_json FROM kmai_factor_mapping_events"))).one()
                assert event == (None, '{"before": null}', '{"after": 1}')
        finally:
            await engine.dispose()

    asyncio.run(run())
