import { describe, expect, it } from 'vitest'

import type {
  KmaiFactorCatalogItem,
  KmaiMappingCreateRequest,
  KmaiMappingUpdateRequest,
} from './kmaiFactorMappings'
import { previewKmaiFactorMappings } from './kmaiFactorMappings'
import type { SaveFinalizedRulePackageResponse } from './extract'
import type { RulePackageV2 } from './rulePackages'

type Assert<T extends true> = T

type PreviewPackageIsV2 = Assert<
  Parameters<typeof previewKmaiFactorMappings>[1] extends RulePackageV2
    ? RulePackageV2 extends Parameters<typeof previewKmaiFactorMappings>[1] ? true : false
    : false
>

type SaveResponseHasRequiredFiles = Assert<
  undefined extends SaveFinalizedRulePackageResponse['kmai_compatibility'] ? false
    : SaveFinalizedRulePackageResponse['kmai_compatibility'] extends { files: Record<string, Record<string, unknown>> }
      ? true
      : false
>

void ({} as PreviewPackageIsV2)
void ({} as SaveResponseHasRequiredFiles)

describe('KmAI mapping API contracts', () => {
  it('requires catalog target value types', () => {
    const booleanFactor: KmaiFactorCatalogItem = {
      factor_key: 'has_slot_feature',
      factor_name: 'Slot feature',
      factor_category: 'feature',
      value_type: 'boolean',
      source_mode: 'builtin',
      read_only: true,
    }

    expect(booleanFactor.value_type).toBe('boolean')
  })

  it('prevents client keys on manual mappings and requires keys on existing mappings', () => {
    // @ts-expect-error Manual factor keys are generated by the server.
    const manualCreate: KmaiMappingCreateRequest = {
      scope: 'project',
      project_id: 7,
      source_field: 'special.requirements',
      source_value: 'Custom requirement',
      mapping_mode: 'manual_factor',
      target_factor_key: 'client_generated',
      target_factor_name: 'Custom requirement',
    }
    // @ts-expect-error Existing-factor mappings need an explicit key.
    const existingCreate: KmaiMappingCreateRequest = {
      scope: 'global',
      source_field: 'cad.features',
      source_value: 'slot',
      mapping_mode: 'existing_factor',
    }
    // @ts-expect-error Manual factor keys are generated by the server.
    const manualUpdate: KmaiMappingUpdateRequest = {
      expected_revision: 1,
      mapping_mode: 'manual_factor',
      target_factor_key: 'client_generated',
    }
    // @ts-expect-error Existing-factor updates need an explicit key.
    const existingUpdate: KmaiMappingUpdateRequest = {
      expected_revision: 1,
      mapping_mode: 'existing_factor',
    }

    expect([manualCreate, existingCreate, manualUpdate, existingUpdate]).toHaveLength(4)
  })
})
