from typing import Literal

from pydantic import Field, model_validator

from app.services.rule_packages.contracts import RulePackageV2, StrictModel


KmaiMappingScope = Literal["global", "project"]
KmaiMappingMode = Literal["existing_factor", "manual_factor"]


class KmaiMappingSnapshot(StrictModel):
    mapping_id: int | None = None
    mapping_identity: str
    revision: int = 1
    scope: Literal["builtin", "global", "project"]
    project_id: int | None = None
    source_field: str
    source_value: str
    mapping_mode: KmaiMappingMode
    target_factor_key: str
    target_factor_name: str
    target_factor_category: str


class KmaiFactorCatalogItem(StrictModel):
    factor_key: str
    factor_name: str
    factor_category: str
    source_mode: str = "catalog"
    read_only: bool = False


class KmaiMappingCreateRequest(StrictModel):
    scope: KmaiMappingScope
    project_id: int | None = None
    source_field: str
    source_value: str
    mapping_mode: KmaiMappingMode
    target_factor_key: str | None = None
    target_factor_name: str | None = None
    target_factor_category: str | None = None
    actor: str = "默认用户"

    @model_validator(mode="after")
    def validate_scope_and_target(self):
        if self.scope == "global" and self.project_id is not None:
            raise ValueError("global mappings cannot have project_id")
        if self.scope == "project" and self.project_id is None:
            raise ValueError("project mappings require project_id")
        if self.mapping_mode == "existing_factor" and not self.target_factor_key:
            raise ValueError("existing_factor mappings require target_factor_key")
        if self.mapping_mode == "manual_factor" and self.target_factor_key is not None:
            raise ValueError("manual_factor target_factor_key is generated by the server")
        return self


class KmaiMappingBatchRequest(StrictModel):
    mappings: list[KmaiMappingCreateRequest] = Field(min_length=1)


class KmaiMappingUpdateRequest(StrictModel):
    expected_revision: int = Field(ge=1)
    mapping_mode: KmaiMappingMode | None = None
    target_factor_key: str | None = None
    target_factor_name: str | None = None
    target_factor_category: str | None = None
    status: Literal["active", "inactive"] | None = None
    actor: str = "默认用户"

    @model_validator(mode="after")
    def validate_manual_target_key(self):
        if self.target_factor_key is not None and self.mapping_mode is None:
            raise ValueError("target_factor_key updates require mapping_mode")
        if self.mapping_mode == "manual_factor" and self.target_factor_key is not None:
            raise ValueError("manual_factor target_factor_key is generated by the server")
        return self


class KmaiMappingOut(KmaiMappingSnapshot):
    status: Literal["active", "inactive"] = "active"
    promoted_from_id: int | None = None
    created_by: str = "默认用户"
    updated_by: str = "默认用户"


class KmaiMappingPreviewRequest(StrictModel):
    package: RulePackageV2
    project_id: int | None = None


class KmaiMappingPreviewResponse(StrictModel):
    valid: bool
    issues: list[dict] = Field(default_factory=list)
    mappings: list[KmaiMappingSnapshot] = Field(default_factory=list)
