import type { LocalStepQuestionProfile } from '@/config/analysisQuestionProfileTypes'
import { buildSettingBasisPrompt, buildTriggerScopePrompt } from '@/config/sharedRulePromptTemplates'

export const SHAPE_STEP_QUESTION_PROFILES: LocalStepQuestionProfile[] = [
  {
    pattern: /^(车零件|车外形)$/,
    profile: {
      key: 'generic_outer_shape',
      logicCategory: 'turning_coarse',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('“车零件/车外形”工序', '回转外形加工对象'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道车削工序存在的条件，主要依赖以下哪类回转类加工对象？',
      structureTypeOptions: [
        { value: 'structure_scene::rough_outer', label: '主回转外形或毛坯外形的粗加工' },
        { value: 'structure_scene::symmetry_outer', label: '一侧/另一侧分开加工的对称端外形' },
        { value: 'structure_scene::profile_outer', label: '台阶、转角或局部轮廓外形加工' },
        { value: 'structure_scene::datum_outer', label: '为后续精加工建立基准外圆或检测外形' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::rough_outer', label: '主要是在做主回转外形或毛坯外形的粗加工' },
        { value: 'structure_scope::symmetry_outer', label: '主要是在分开加工一侧/另一侧的对称端外形' },
        { value: 'structure_scope::profile_outer', label: '主要是在加工台阶、转角或局部轮廓外形' },
        { value: 'structure_scope::datum_outer', label: '主要是在为后续精加工建立基准外圆或检测外形' },
      ],
      requirementTypePrompt: '如果不主要由回转外形决定，请确认它存在的条件，主要依赖以下哪类基础尺寸或后续精加工准备需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::rough_allowance', label: '需要先把毛坯余量和基础外形粗开出来' },
        { value: 'requirement_scene::split_setup', label: '需要先建立稳定的装夹或检测基准外形' },
        { value: 'requirement_scene::followup_finish', label: '需要为后续精车、磨削或检验预留稳定余量' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('“车零件/车外形”工序', '基础尺寸或后续精加工准备需求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::rough_allowance', label: '主要由毛坯余量较大，需要先做外形粗开驱动' },
        { value: 'requirement_scope::split_setup', label: '主要由先建立装夹或检测基准外形驱动' },
        { value: 'requirement_scope::followup_finish', label: '主要由为后续精车、磨削或检验预留余量驱动' },
      ],
    },
  },
  {
    pattern: /(端面|车端面|精车端面|磨端面)/,
    profile: {
      key: 'end_face_role',
      logicCategory: 'turning_coarse',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('端面加工工序', '端面加工对象'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道端面加工工序存在的条件，主要依赖以下哪类端面角色或端面加工要求？',
      structureTypeOptions: [
        { value: 'structure_scene::datum_face', label: '基准端面或定位端面' },
        { value: 'structure_scene::fit_face', label: '贴合端面或配合端面' },
        { value: 'structure_scene::hole_mouth_face', label: '孔口端面或沉台端面' },
        { value: 'structure_scene::length_face', label: '用于保证总长或端面距的控制端面' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::datum_face', label: '主要是在建立基准端面或定位端面' },
        { value: 'structure_scope::fit_face', label: '主要是在形成贴合端面或配合端面' },
        { value: 'structure_scope::hole_mouth_face', label: '主要是在处理孔口端面或沉台端面' },
        { value: 'structure_scope::length_face', label: '主要是在控制总长或关键端面距' },
      ],
      requirementTypePrompt: '如果不主要由端面角色决定，请确认它存在的条件，主要依赖以下哪类尺寸、基准或装配需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::length_control', label: '需要控制总长、端面距或尺寸链' },
        { value: 'requirement_scene::perpendicularity', label: '需要建立稳定端面基准或端面关系' },
        { value: 'requirement_scene::assembly_fit', label: '需要满足贴合、密封或装配要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('端面工序', '精度或装配要求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::length_control', label: '需要控制总长、端面距或相关尺寸链' },
        { value: 'requirement_scope::perpendicularity', label: '需要保证平面度、垂直度或端面跳动' },
        { value: 'requirement_scope::assembly_fit', label: '需要满足装配贴合、密封或贴靠要求' },
      ],
    },
  },
  {
    pattern: /(车槽|切槽|环槽|退刀槽|越程槽|密封槽|键槽|花键槽|铣槽|槽加工|外环槽|内环槽)/,
    profile: {
      key: 'groove_feature',
      logicCategory: 'turning_coarse',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('槽加工工序', '槽结构'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道槽加工工序主要受哪类槽部结构特征触发？',
      structureTypeOptions: [
        { value: 'structure_scene::relief_groove', label: '退刀槽、越程槽或让刀槽' },
        { value: 'structure_scene::seal_groove', label: '密封槽、卡簧槽或功能环槽' },
        { value: 'structure_scene::key_slot', label: '键槽、花键槽或传动槽' },
        { value: 'structure_scene::common_ring_groove', label: '一般内外环槽或局部凹槽' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::relief_groove', label: '主要是在加工退刀槽、越程槽或让刀槽' },
        { value: 'structure_scope::seal_groove', label: '主要是在加工密封槽、卡簧槽或功能环槽' },
        { value: 'structure_scope::key_slot', label: '主要是在加工键槽、花键槽或传动槽' },
        { value: 'structure_scope::common_ring_groove', label: '主要是在加工一般内外环槽或局部凹槽' },
      ],
      requirementTypePrompt: '如果不主要由槽结构决定，请确认它存在的条件，主要依赖以下哪类尺寸、功能或装配需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::fit_groove', label: '槽宽、槽深或配合尺寸控制要求' },
        { value: 'requirement_scene::seal_function', label: '密封、卡簧或限位功能要求' },
        { value: 'requirement_scene::transmission', label: '传动、定位或联接功能要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('槽加工工序', '功能或精度要求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::fit_groove', label: '需要控制槽宽、槽深或相关配合尺寸' },
        { value: 'requirement_scope::seal_function', label: '需要满足密封、卡簧或限位功能' },
        { value: 'requirement_scope::transmission', label: '需要满足传动、定位或联接功能' },
      ],
    },
  },
  {
    pattern: /(车外圆|车外形|车零件|粗车外圆|半精车外圆|外圆车削|车削类孔?加工|外形车削)/,
    profile: {
      key: 'outer_surface_general',
      logicCategory: 'turning_coarse',
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('外圆加工工序', '外圆加工对象'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道外圆加工工序存在的条件，主要依赖以下哪类外圆表面或回转外形？',
      structureTypeOptions: [
        { value: 'structure_scene::main_outer', label: '主外圆或回转主形面' },
        { value: 'structure_scene::step_outer', label: '台阶外圆、轴肩或局部轮廓外圆' },
        { value: 'structure_scene::datum_outer', label: '定位基准外圆或检测基准外圆' },
        { value: 'structure_scene::fit_outer', label: '关键配合外圆或定尺寸外圆' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::main_outer', label: '主要是在加工主外圆或回转主形面' },
        { value: 'structure_scope::step_outer', label: '主要是在加工台阶外圆、轴肩或局部轮廓外圆' },
        { value: 'structure_scope::datum_outer', label: '主要是在建立定位基准外圆或检测基准外圆' },
        { value: 'structure_scope::fit_outer', label: '主要是在加工关键配合外圆或定尺寸外圆' },
      ],
      requirementTypePrompt: '如果不主要由外圆结构决定，请确认它存在的条件，主要依赖以下哪类基础尺寸或后续精加工准备需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::rough_allowance', label: '需要先把外圆余量和基础尺寸粗开出来' },
        { value: 'requirement_scene::split_setup', label: '需要先建立装夹、检测或定位用的外圆基准' },
        { value: 'requirement_scene::followup_finish', label: '需要为后续精车、磨削或检验预留稳定余量' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('外圆工序', '基础尺寸或后续精加工准备需求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::rough_allowance', label: '主要由先粗开外圆余量和基础尺寸驱动' },
        { value: 'requirement_scope::split_setup', label: '主要由先建立装夹、检测或定位用的外圆基准驱动' },
        { value: 'requirement_scope::followup_finish', label: '主要由为后续精车、磨削或检验预留余量驱动' },
      ],
    },
  },
  {
    pattern: /(铣扁|割扁|磨扁|铣平面|对边加工)/,
    profile: {
      key: 'flat_feature',
      logicCategory: 'milling_coarse',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('铣扁/割扁工序', '扁位或平面加工对象'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道平面或扁位加工工序存在的条件，主要依赖以下哪类加工对象？',
      structureTypeOptions: [
        { value: 'structure_scene::anti_rotation_flat', label: '防转扁位、夹持扁位或装夹平面' },
        { value: 'structure_scene::across_flat', label: '对边尺寸、局部削平或外形平面' },
        { value: 'structure_scene::datum_flat', label: '定位平面、检测平面或工艺基准平面' },
        { value: 'structure_scene::clearance_flat', label: '让位平面、避让平面或局部清根平面' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::anti_rotation_flat', label: '主要是在加工防转扁位、夹持扁位或装夹平面' },
        { value: 'structure_scope::across_flat', label: '主要是在控制对边尺寸、局部削平或外形平面' },
        { value: 'structure_scope::datum_flat', label: '主要是在建立定位平面、检测平面或工艺基准平面' },
        { value: 'structure_scope::clearance_flat', label: '主要是在加工让位平面、避让平面或局部清根平面' },
      ],
      requirementTypePrompt: '如果不主要由扁位或平面结构决定，请确认它存在的条件，主要依赖以下哪类尺寸、定位或装夹需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::flat_size', label: '对边尺寸、平面尺寸或平面余量控制要求' },
        { value: 'requirement_scene::flat_datum', label: '定位、检测或装夹基准要求' },
        { value: 'requirement_scene::flat_clearance', label: '让位、避让或局部清根要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('铣扁/割扁工序', '尺寸、定位或装夹要求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::flat_size', label: '需要控制对边尺寸、平面尺寸或平面余量' },
        { value: 'requirement_scope::flat_datum', label: '需要建立定位、检测或装夹基准平面' },
        { value: 'requirement_scope::flat_clearance', label: '需要满足让位、避让或局部清根' },
      ],
    },
  },
]
