import type { LocalStepQuestionProfile } from '@/config/analysisQuestionProfileTypes'
import { buildSettingBasisPrompt, buildTriggerScopePrompt } from '@/config/sharedRulePromptTemplates'

export const SUPPORT_STEP_QUESTION_PROFILES: LocalStepQuestionProfile[] = [
  {
    pattern: /^除油$/,
    profile: {
      key: 'hffm_degrease',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道“除油”没有覆盖全部样本时，主要由哪类后续处理或洁净要求决定？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::material',
        'coverage_reason::structure',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道“除油”主要服务于哪类工艺目的？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::before_alodine', label: '后续需要阿洛丁/化学转化膜，必须先除油' },
        { value: 'hffm_requirement::before_assembly', label: '导管镶装或装配前，需要去除油污保证结合/密封' },
        { value: 'hffm_requirement::cleanliness', label: '有氧气禁油、内腔洁净或污染控制要求' },
        { value: 'hffm_requirement::before_paint', label: '喷漆或表面处理前，需要做表面预处理' },
      ],
      requirementScopePrompt: '请确认当前样本中“除油”出现的具体触发场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::before_alodine', label: '主要出现在阿洛丁/化学转化膜处理前' },
        { value: 'hffm_scope::before_assembly', label: '主要出现在导管镶装或装配前' },
        { value: 'hffm_scope::cleanliness', label: '主要由洁净、禁油或污染控制要求触发' },
        { value: 'hffm_scope::before_paint', label: '主要出现在喷漆或表面处理前' },
      ],
    },
  },
  {
    pattern: /^阿洛丁$/,
    profile: {
      key: 'hffm_alodine',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道“阿洛丁”没有覆盖全部样本时，主要由哪类表面防护或后续处理要求决定？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::material',
        'coverage_reason::structure',
      ],
      requirementTypePrompt: '这道“阿洛丁”主要服务于哪类工艺目的？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::conversion_coating', label: '铝合金表面需要化学转化膜/防腐蚀保护' },
        { value: 'hffm_requirement::paint_pretreat', label: '作为喷漆或涂层前的表面预处理' },
        { value: 'hffm_requirement::assembly_surface', label: '装配或镶装区域需要表面状态控制' },
        { value: 'hffm_requirement::document_required', label: '由工艺卡或技术条件明确要求' },
      ],
      requirementScopePrompt: '请确认当前样本中“阿洛丁”出现的具体触发场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::conversion_coating', label: '主要由铝合金表面防腐蚀/转化膜要求触发' },
        { value: 'hffm_scope::paint_pretreat', label: '主要用于喷漆或涂层前处理' },
        { value: 'hffm_scope::assembly_surface', label: '主要用于装配区域的表面状态控制' },
        { value: 'hffm_scope::document_required', label: '主要因为工艺卡或技术条件明确列出' },
      ],
    },
  },
  {
    pattern: /^导管配套$/,
    profile: {
      key: 'hffm_tube_kitting',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: '这道“导管配套”主要由哪类装配准备关系决定？',
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::material',
      ],
      structureTypePrompt: '这道“导管配套”主要对应哪类配套对象？',
      structureTypeOptions: [
        { value: 'hffm_structure::tube_connector_pair', label: '导管与接头/管嘴需要配套确认' },
        { value: 'hffm_structure::multi_part_set', label: '多件或成套导管需要成组流转' },
        { value: 'hffm_structure::assembly_position', label: '按装配位置、方向或编号进行配套' },
        { value: 'hffm_structure::test_fixture_prepare', label: '为后续镶装、试验或清洗准备配套件' },
      ],
      structureScopeFallbacks: [
        { value: 'hffm_scope::tube_connector_pair', label: '主要是导管与接头/管嘴配套' },
        { value: 'hffm_scope::multi_part_set', label: '主要是成套导管分组流转' },
        { value: 'hffm_scope::assembly_position', label: '主要按装配位置或编号配套' },
        { value: 'hffm_scope::test_fixture_prepare', label: '主要为后续镶装或试验准备配套件' },
      ],
    },
  },
  {
    pattern: /^导管镶装$/,
    profile: {
      key: 'hffm_tube_assembly',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: '这道“导管镶装”主要由哪类导管连接或装配结构决定？',
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::material',
      ],
      structureTypePrompt: '这道“导管镶装”主要对应哪类连接结构？',
      structureTypeOptions: [
        { value: 'hffm_structure::insert_connector', label: '导管与接头/管嘴存在镶装连接' },
        { value: 'hffm_structure::sealed_joint', label: '连接处承担密封或耐压功能' },
        { value: 'hffm_structure::assembly_position', label: '按装配位置、方向或配套关系进行连接' },
        { value: 'hffm_structure::special_joint', label: '特殊接头、堵头或试验接口需要装配' },
      ],
      structureScopeFallbacks: [
        { value: 'hffm_scope::insert_connector', label: '主要是导管与接头/管嘴镶装' },
        { value: 'hffm_scope::sealed_joint', label: '主要由密封或耐压连接要求触发' },
        { value: 'hffm_scope::assembly_position', label: '主要由装配位置、方向或配套关系触发' },
        { value: 'hffm_scope::special_joint', label: '主要由特殊接头、堵头或试验接口触发' },
      ],
    },
  },
  {
    pattern: /^气密试验$/,
    profile: {
      key: 'hffm_leak_test',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道“气密试验”主要由哪类密封或耐压验证要求决定？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
      ],
      requirementTypePrompt: '这道“气密试验”主要验证哪类要求？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::leak_tightness', label: '导管或接头连接后需要验证泄漏/气密性' },
        { value: 'hffm_requirement::pressure_boundary', label: '零件属于压力边界或需承受规定试验压力' },
        { value: 'hffm_requirement::post_assembly_check', label: '镶装或装配后需要做功能放行验证' },
        { value: 'hffm_requirement::safety_critical', label: '气路/油路/氧气系统等安全关键通路需要验证' },
      ],
      requirementScopePrompt: '请确认当前样本中“气密试验”出现的具体触发场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::leak_tightness', label: '主要用于验证导管或接头连接后的泄漏/气密性' },
        { value: 'hffm_scope::pressure_boundary', label: '主要由试验压力或压力边界要求触发' },
        { value: 'hffm_scope::post_assembly_check', label: '主要作为镶装或装配后的功能放行验证' },
        { value: 'hffm_scope::safety_critical', label: '主要由安全关键通路验证要求触发' },
      ],
    },
  },
  {
    pattern: /^导管清洗$/,
    profile: {
      key: 'hffm_tube_cleaning',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道“导管清洗”主要由哪类导管洁净或交付状态要求决定？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
      ],
      requirementTypePrompt: '这道“导管清洗”主要服务于哪类要求？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::internal_cleanliness', label: '导管内腔洁净度或污染控制要求' },
        { value: 'hffm_requirement::after_assembly_clean', label: '镶装、试验或喷漆前后需要清除残留' },
        { value: 'hffm_requirement::delivery_clean', label: '最终检验、封存或交付前需要达到清洁状态' },
        { value: 'hffm_requirement::oxygen_clean', label: '禁油、氧气系统或高洁净通路要求' },
      ],
      requirementScopePrompt: '请确认当前样本中“导管清洗”出现的具体触发场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::internal_cleanliness', label: '主要由导管内腔洁净度或污染控制要求触发' },
        { value: 'hffm_scope::after_assembly_clean', label: '主要用于镶装、试验或喷漆前后清除残留' },
        { value: 'hffm_scope::delivery_clean', label: '主要用于最终检验、封存或交付前清洁' },
        { value: 'hffm_scope::oxygen_clean', label: '主要由禁油、氧气系统或高洁净要求触发' },
      ],
    },
  },
  {
    pattern: /^喷漆$/,
    profile: {
      key: 'hffm_paint',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道“喷漆”主要由哪类表面防护或标识要求决定？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::material',
        'coverage_reason::structure',
      ],
      requirementTypePrompt: '这道“喷漆”主要服务于哪类要求？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::surface_protection', label: '防腐蚀、防护或环境适应性要求' },
        { value: 'hffm_requirement::paint_system', label: '图纸或技术条件规定的涂层体系要求' },
        { value: 'hffm_requirement::identification', label: '颜色、区域或状态标识要求' },
        { value: 'hffm_requirement::post_alodine_chain', label: '阿洛丁后需要继续完成表面涂装链' },
      ],
      requirementScopePrompt: '请确认当前样本中“喷漆”出现的具体触发场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::surface_protection', label: '主要由防腐蚀、防护或环境适应性要求触发' },
        { value: 'hffm_scope::paint_system', label: '主要由图纸或技术条件规定的涂层体系触发' },
        { value: 'hffm_scope::identification', label: '主要由颜色、区域或状态标识要求触发' },
        { value: 'hffm_scope::post_alodine_chain', label: '主要是阿洛丁后的表面涂装链' },
      ],
    },
  },
  {
    pattern: /^(总检|最终检验|均质检验)$/,
    profile: {
      key: 'hffm_inspection',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: '这道检验工序主要控制哪类 HFFM 工艺放行关口？',
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
      ],
      requirementTypePrompt: '这道检验工序主要用于哪类放行确认？',
      requirementTypeOptions: [
        { value: 'hffm_requirement::process_quality_gate', label: '成形、镶装或表面处理后的过程质量确认' },
        { value: 'hffm_requirement::final_release', label: '最终检验或交付前综合放行' },
        { value: 'hffm_requirement::special_quality', label: '均质性、外观或专项质量要求确认' },
        { value: 'hffm_requirement::document_compliance', label: '确认工艺卡和技术条件要求均已满足' },
      ],
      requirementScopePrompt: '请确认当前样本中该检验工序出现的具体放行场景。',
      requirementScopeFallbacks: [
        { value: 'hffm_scope::process_quality_gate', label: '主要用于过程质量确认' },
        { value: 'hffm_scope::final_release', label: '主要用于最终检验或交付前综合放行' },
        { value: 'hffm_scope::special_quality', label: '主要用于均质性、外观或专项质量确认' },
        { value: 'hffm_scope::document_compliance', label: '主要用于确认工艺卡和技术条件符合性' },
      ],
    },
  },
  {
    pattern: /(倒角|倒圆|孔口倒角|车倒角|外倒角|内倒角)/,
    profile: {
      key: 'chamfer_edge',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::structure',
      rootPrompt: buildSettingBasisPrompt('倒角/倒圆工序', '边缘处理需求'),
      rootReasonOrder: [
        'coverage_reason::structure',
        'coverage_reason::requirement',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      structureTypePrompt: '这道边缘处理工序存在的条件，主要依赖以下哪类边缘或孔口处理场景？',
      structureTypeOptions: [
        { value: 'structure_scene::sharp_edge', label: '锐边、毛刺或边缘过渡处理' },
        { value: 'structure_scene::hole_entry', label: '孔口导入或孔口倒角' },
        { value: 'structure_scene::assembly_entry', label: '装配导入、防划伤或导向边' },
        { value: 'structure_scene::seal_edge', label: '密封口、贴合边缘或保护边' },
      ],
      structureScopeFallbacks: [
        { value: 'structure_scope::sharp_edge', label: '主要是在去除锐边、毛刺或做边缘过渡' },
        { value: 'structure_scope::hole_entry', label: '主要是在处理孔口导入或孔口倒角' },
        { value: 'structure_scope::assembly_entry', label: '主要是在满足装配导入或防划伤要求' },
        { value: 'structure_scope::seal_edge', label: '主要是在保护密封口或贴合边缘' },
      ],
      requirementTypePrompt: '如果不主要由边缘结构决定，请确认倒角工序存在的条件，主要依赖以下哪类功能或质量要求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::surface', label: '边缘质量、去毛刺或表面完整性要求' },
        { value: 'requirement_scene::assembly', label: '装配导入、防磕碰或配合保护要求' },
        { value: 'requirement_scene::seal', label: '密封或贴合边缘保护要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('倒角/倒圆工序', '功能或质量要求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::edge_quality', label: '需要去除锐边、毛刺或保护边缘质量' },
        { value: 'requirement_scope::assembly_entry', label: '需要装配导入、防磕碰或避免刮伤' },
        { value: 'requirement_scope::seal_protect', label: '需要保护密封口或贴合边缘' },
      ],
    },
  },
  {
    pattern: /^(检验|终检)$/,
    profile: {
      key: 'generic_inspection',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('检验工序', '通用质量关口'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道检验工序主要用于控制哪类质量关口？',
      requirementTypeOptions: [
        { value: 'requirement_gate::process_check', label: '粗加工或中间转序后的过程检验点' },
        { value: 'requirement_gate::pre_finish', label: '热处理后或精加工前的状态确认点' },
        { value: 'requirement_gate::finish_confirm', label: '精加工后尺寸、形位或表面状态确认点' },
        { value: 'requirement_gate::final_check', label: '终检、入库或交付前综合检验点' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('检验工序', '通用质量关口'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::process_check', label: '主要用于粗加工或中间转序后的过程检验' },
        { value: 'requirement_scope::pre_finish', label: '主要用于热处理后或精加工前的状态确认' },
        { value: 'requirement_scope::finish_confirm', label: '主要用于精加工后尺寸、形位或表面状态确认' },
        { value: 'requirement_scope::final_check', label: '主要用于终检、入库或交付前综合检验' },
      ],
    },
  },
  {
    pattern: /(烧伤检查|磁粉检查|裂纹检查|荧光检查|渗透检验|外观检查|检验|终检)/,
    profile: {
      key: 'inspection_gate',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('专项检测工序', '质量关口'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道专项检验工序主要用于控制哪类质量关口？',
      requirementTypeOptions: [
        { value: 'requirement_gate::process_check', label: '车削后或周边加工后的过程检验点' },
        { value: 'requirement_gate::burn_check', label: '淬火后烧伤风险检查' },
        { value: 'requirement_gate::ndt_mt', label: '磁粉、裂纹等专项无损检测要求' },
        { value: 'requirement_gate::penetrant', label: '渗氮后渗透检验或表面缺陷检查' },
        { value: 'requirement_gate::final_check', label: '终检或交付前综合检验' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('检验/检查工序', '质量关口'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::process_check', label: '用于车削后或周边加工后的过程检验' },
        { value: 'requirement_scope::burn_check', label: '用于淬火后烧伤风险检查' },
        { value: 'requirement_scope::ndt_mt', label: '用于磁粉、裂纹等专项无损检测' },
        { value: 'requirement_scope::penetrant', label: '用于渗氮后渗透检验或表面缺陷检查' },
        { value: 'requirement_scope::final_check', label: '用于终检或交付前综合检验' },
      ],
    },
  },
  {
    pattern: /(去毛刺|清洗)/,
    profile: {
      key: 'cleanup_stage',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('去毛刺/清洗工序', '转序节点'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::size',
        'coverage_reason::material',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道去毛刺或清洗工序主要服务于哪类转序节点？',
      requirementTypeOptions: [
        { value: 'requirement_stage::after_turning', label: '车削或机械加工后，需要清理毛刺和残留' },
        { value: 'requirement_stage::before_check', label: '检验或专项检查前，需要清洗或清理表面' },
        { value: 'requirement_stage::after_special', label: '热处理、渗氮或表面处理后，需要清洗或去残留' },
        { value: 'requirement_stage::before_release', label: '终检前或交付前，需要最终清理' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('去毛刺/清洗工序', '转序节点'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::after_turning', label: '主要安排在车削或机械加工后做清理' },
        { value: 'requirement_scope::before_check', label: '主要安排在检验或专项检查前做清理' },
        { value: 'requirement_scope::after_special', label: '主要安排在热处理、渗氮或表面处理后做清理' },
        { value: 'requirement_scope::before_release', label: '主要安排在终检前或交付前做最终清理' },
      ],
    },
  },
  {
    pattern: /(标印|打标|标记)/,
    profile: {
      key: 'trace_mark',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('标印工序', '标识需求'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道标识工序主要服务于哪类标识或追溯需求？',
      requirementTypeOptions: [
        { value: 'requirement_mark::trace', label: '零件追溯、编号或批次标识需求' },
        { value: 'requirement_mark::assembly', label: '装配方向、安装位置或配对标识需求' },
        { value: 'requirement_mark::process', label: '工艺状态、热处理状态或检验状态标识需求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('标印工序', '标识需求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::trace', label: '主要用于零件追溯、编号或批次标识' },
        { value: 'requirement_scope::assembly', label: '主要用于装配方向、安装位置或配对标识' },
        { value: 'requirement_scope::process', label: '主要用于工艺状态、热处理状态或检验状态标识' },
      ],
    },
  },
  {
    pattern: /(包装|防护包装|封存)/,
    profile: {
      key: 'package_release',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('包装/封存工序', '交付、防护或转运需求'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::structure',
        'coverage_reason::material',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道交付收尾工序主要服务于哪类交付或防护需求？',
      requirementTypeOptions: [
        { value: 'requirement_scene::delivery', label: '终检后交付、转运或入库需求' },
        { value: 'requirement_scene::surface_protect', label: '防锈、防碰伤或表面保护需求' },
        { value: 'requirement_scene::trace_release', label: '包装前标识、配套或交接需求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('包装/封存工序', '交付或防护需求'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::delivery', label: '主要用于终检后交付、转运或入库' },
        { value: 'requirement_scope::surface_protect', label: '主要用于防锈、防碰伤或表面保护' },
        { value: 'requirement_scope::trace_release', label: '主要用于包装前标识、配套或交接' },
      ],
    },
  },
  {
    pattern: /^表面处理$/,
    profile: {
      key: 'surface_treat_generic',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('表面处理工序', '表面保护或后续处理链需求'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::material',
        'coverage_reason::structure',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道表面处理工序主要服务于哪类表面处理目标？',
      requirementTypeOptions: [
        { value: 'requirement_scene::surface_protect', label: '防护、防腐蚀、绝缘或表面稳定性要求' },
        { value: 'requirement_scene::process_masking', label: '渗氮、选择性处理或局部屏蔽辅助要求' },
        { value: 'requirement_scene::surface_chain', label: '后续表面处理链、返工链或清除辅助层要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('表面处理工序', '表面保护或工艺辅助目标'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::surface_protect', label: '主要用于防护、防腐蚀、绝缘或表面稳定性处理' },
        { value: 'requirement_scope::process_masking', label: '主要用于渗氮、选择性处理或局部屏蔽辅助' },
        { value: 'requirement_scope::surface_chain', label: '主要用于后续表面处理链、返工链或清除辅助层' },
      ],
      materialTypePrompt: '如果和材料有关，请确认它主要受哪类材料或表面状态边界影响？',
      materialTypeOptions: [
        { value: 'material_basis::grade', label: '按材料牌号或基体材料' },
        { value: 'material_basis::class', label: '按材料类别或表面状态类别' },
      ],
    },
  },
  {
    pattern: /(镀铜|除铜|铬酸阳极化|硬质阳极化|钝化)/,
    profile: {
      key: 'surface_treat_single',
      logicCategory: 'special',
      skipRequirementScopeAfterType: true,
      directRootValue: 'coverage_reason::requirement',
      rootPrompt: buildSettingBasisPrompt('该表面处理工序', '表面保护、选择性屏蔽或后续工艺链需求'),
      rootReasonOrder: [
        'coverage_reason::requirement',
        'coverage_reason::material',
        'coverage_reason::structure',
        'coverage_reason::size',
        'coverage_reason::blank',
      ],
      requirementTypePrompt: '这道表面处理工序主要服务于哪类表面处理目标？',
      requirementTypeOptions: [
        { value: 'requirement_scene::surface_protect', label: '防护、防腐蚀、绝缘或表面稳定性要求' },
        { value: 'requirement_scene::process_masking', label: '渗氮、选择性处理或局部屏蔽辅助要求' },
        { value: 'requirement_scene::surface_chain', label: '后续表面处理链、返工链或清除辅助层要求' },
      ],
      requirementScopePrompt: buildTriggerScopePrompt('该表面处理工序', '表面保护或工艺辅助目标'),
      requirementScopeFallbacks: [
        { value: 'requirement_scope::surface_protect', label: '主要用于防护、防腐蚀、绝缘或表面稳定性处理' },
        { value: 'requirement_scope::process_masking', label: '主要用于渗氮、选择性处理或局部屏蔽辅助' },
        { value: 'requirement_scope::surface_chain', label: '主要用于后续表面处理链、返工链或清除辅助层' },
      ],
      materialTypePrompt: '如果和材料有关，请确认它主要受哪类材料或表面状态边界影响？',
      materialTypeOptions: [
        { value: 'material_basis::grade', label: '按材料牌号或基体材料' },
        { value: 'material_basis::class', label: '按材料类别或表面状态类别' },
      ],
    },
  },
]
