/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisRouteList: typeof import('./components/analysis/AnalysisRouteList.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    EvidenceExcerptPanel: typeof import('./components/analysis/EvidenceExcerptPanel.vue')['default']
    EvidenceRowsPanel: typeof import('./components/analysis/EvidenceRowsPanel.vue')['default']
    ExtractActionFooter: typeof import('./components/extract/ExtractActionFooter.vue')['default']
    ExtractPageHeader: typeof import('./components/extract/ExtractPageHeader.vue')['default']
    ExtractRouteActionFooter: typeof import('./components/extract/ExtractRouteActionFooter.vue')['default']
    ExtractRouteShellHeader: typeof import('./components/extract/ExtractRouteShellHeader.vue')['default']
    ExtractStatusCard: typeof import('./components/extract/ExtractStatusCard.vue')['default']
    FinalizeRouteNav: typeof import('./components/finalize/FinalizeRouteNav.vue')['default']
    FinalizeRuleCard: typeof import('./components/finalize/FinalizeRuleCard.vue')['default']
    GenerateInputPanel: typeof import('./components/generate/GenerateInputPanel.vue')['default']
    GenerateRouteOutputPanel: typeof import('./components/generate/GenerateRouteOutputPanel.vue')['default']
    MergeQueuePanel: typeof import('./components/extract/MergeQueuePanel.vue')['default']
    ModelSettingsDrawer: typeof import('./components/settings/ModelSettingsDrawer.vue')['default']
    NormalizedRoutePanel: typeof import('./components/extract/NormalizedRoutePanel.vue')['default']
    QuestionTreePanel: typeof import('./components/analysis/QuestionTreePanel.vue')['default']
    RouteProgressCard: typeof import('./components/extract/RouteProgressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleComparePanel: typeof import('./components/analysis/SampleComparePanel.vue')['default']
    SourceRoutePanel: typeof import('./components/extract/SourceRoutePanel.vue')['default']
    UploadMainFileCard: typeof import('./components/upload/UploadMainFileCard.vue')['default']
    UploadProjectBoard: typeof import('./components/upload/UploadProjectBoard.vue')['default']
    UploadReferenceCard: typeof import('./components/upload/UploadReferenceCard.vue')['default']
    WorkflowNavFooter: typeof import('./components/workflow/WorkflowNavFooter.vue')['default']
  }
}
